# Generated by Django 6.0.1 on 2026-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='profile_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actress',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
