# Generated by Django 6.0.1 on 2026-03-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actresses', '0002_actress_profile_path_alter_actress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
